# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ matrix.node-version }}
      TEST_ENV: true

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: BackAttenza/package-lock.json
      - name: Checkout submodules
        run: |
            git submodule init
            git submodule update
      - name: Create config.json
        run: echo "${{ secrets.CONFIG_JSON }}" | base64 --decode > config.json
        working-directory: BackAttenza
      - name: Create cert.pem
        run: echo "${{ secrets.CERT_PEM }}" | base64 --decode > cert.pem
        working-directory: BackAttenza
      - name: Create key.pem
        run: echo "${{ secrets.KEY_PEM }}" | base64 --decode > key.pem
        working-directory: BackAttenza
      - name: Install Dependencies
        run: npm ci
        working-directory: BackAttenza
      - name: Build
        run: npm run build --if-present
        working-directory: BackAttenza
      - name: Test
        run: npm test
        working-directory: BackAttenza
